version: "3"
services:
  web:
    container_name: web_app
    build: .
    command:
      npm start
    depends_on:
      - server
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "5000:5000"
